import '../l10n/generated/app_localizations.dart';
import '../services/markdown_exporter.dart';

/// 从本地化资源构建导出文案。
///
/// 带数值的行通过“令牌回填”生成模板：ARB 消息中的占位符
/// （如 `{count}`）在这里传入字面令牌字符串，得到含 `{token}` 的模板，
/// 导出器写入文件前再把令牌替换为实际数值。
ExportLabels localizedExportLabels(AppLocalizations l10n) => ExportLabels(
  paperFileName: l10n.exportPaperFileName,
  answersFileName: l10n.exportAnswersFileName,
  reviewFileName: l10n.exportReviewFileName,
  answerSheetFileName: l10n.exportAnswerSheetFileName,
  resourcesFolderName: l10n.exportResourcesFolderName,
  answersYamlSuffix: l10n.exportAnswersYamlSuffix,
  answersHeadingSuffix: l10n.exportAnswersHeadingSuffix,
  reviewYamlSuffix: l10n.exportReviewYamlSuffix,
  reviewHeadingSuffix: l10n.exportReviewHeadingSuffix,
  paperStatsLine: l10n.exportPaperStatsLine('{count}', '{minutes}'),
  multipleChoiceTag: l10n.exportMultipleChoiceTag,
  singleChoiceTag: l10n.exportSingleChoiceTag,
  missingMediaWarning: l10n.exportMissingMediaWarning('{path}'),
  correctAnswersBoldLine: l10n.exportCorrectAnswersBoldLine('{answers}'),
  explanationLine: l10n.exportExplanationLine('{explanation}'),
  knowledgePointSourceLine: l10n.exportKnowledgePointSourceLine(
    '{knowledgePoint}',
    '{source}',
  ),
  reviewScoreLine: l10n.exportReviewScoreLine('{score}', '{max}'),
  totalDurationLine: l10n.exportTotalDurationLine('{duration}'),
  overtimeLine: l10n.exportOvertimeLine('{duration}'),
  unansweredCountLine: l10n.exportUnansweredCountLine('{count}'),
  unansweredStatus: l10n.exportUnansweredStatus,
  fullyCorrectStatus: l10n.exportFullyCorrectStatus,
  wrongStatus: l10n.exportWrongStatus,
  verdictLine: l10n.exportVerdictLine('{status}'),
  userSelectionLine: l10n.exportUserSelectionLine('{answers}'),
  correctAnswerLine: l10n.exportCorrectAnswerLine('{answers}'),
  questionDurationLine: l10n.exportQuestionDurationLine('{duration}'),
  favoriteUncertainLine: l10n.exportFavoriteUncertainLine(
    '{favorite}',
    '{uncertain}',
  ),
  yesLabel: l10n.exportYesLabel,
  noLabel: l10n.exportNoLabel,
  personalNoteLine: l10n.exportPersonalNoteLine('{note}'),
  emptyNoteValue: l10n.exportEmptyNoteValue,
  knowledgePointSourceReviewLine: l10n.exportKnowledgePointSourceReviewLine(
    '{knowledgePoint}',
    '{source}',
  ),
  answerSeparator: l10n.exportAnswerSeparator,
  answerSheetYamlSuffix: l10n.exportAnswerSheetYamlSuffix,
  answerSheetHeadingSuffix: l10n.exportAnswerSheetHeadingSuffix,
  answerSheetStatsLine: l10n.exportAnswerSheetStatsLine(
    '{count}',
    '{single}',
    '{multiple}',
  ),
  answerSheetQrAlt: l10n.exportAnswerSheetQrAlt,
  fillNoteHtml: l10n.exportFillNoteHtml,
  answerSectionTitle: l10n.exportAnswerSectionTitle,
  answerSectionHint: l10n.exportAnswerSectionHint,
  questionNumberHeader: l10n.exportQuestionNumberHeader,
  wrongQuestionsTitle: l10n.exportWrongQuestionsTitle,
  recentSelectionLine: l10n.exportRecentSelectionLine('{answers}'),
  knowledgePointLine: l10n.exportKnowledgePointLine('{knowledgePoint}'),
  sourceLine: l10n.exportSourceLine('{source}'),
  attemptStatsLine: l10n.exportAttemptStatsLine('{seen}', '{wrong}'),
  qaTag: l10n.exportQaTag,
  qaReferenceAnswerLine: l10n.exportQaReferenceAnswerLine('{answer}'),
  qaEmptyReferenceAnswer: l10n.exportQaEmptyReferenceAnswer,
  qaUserAnswerLine: l10n.exportQaUserAnswerLine('{answer}'),
  qaUnansweredText: l10n.exportQaUnansweredText,
  answerSheetQaSectionTitle: l10n.exportAnswerSheetQaSectionTitle,
  answerSheetQaItemLabel: l10n.exportAnswerSheetQaItemLabel('{number}'),
  answerSheetQaOverflowNote: l10n.exportAnswerSheetQaOverflowNote,
  answerSheetQaStatsSuffix: l10n.exportAnswerSheetQaStatsSuffix('{qa}'),
);
